# Site settings
title: Varez Yeyez Portofolio
email: varez.yeyez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "varezy.github.io" # the base hostname & protocol for your site

twitter_username: varez.yeyez
github_username: VarezY

# Build settings
markdown: kramdown
